/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leticia.lanchonete.view;

import com.leticia.lanchonete.model.Pedido;
import javax.swing.JOptionPane;

/**
 *
 * @author letno
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrameCadastroPedido = new javax.swing.JInternalFrame();
        jLabelCadastroPedido = new javax.swing.JLabel();
        jTextFieldCadastroPedidoNome = new javax.swing.JTextField();
        jLabelCadastroPedidoPreco = new javax.swing.JLabel();
        jTextFieldCadastroPedidoPreco = new javax.swing.JTextField();
        jButtonCadastroPedidoSalvar = new javax.swing.JButton();
        jButtonCadastroCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroPedido = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemEditarPedido = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarPedido = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanchonete da Letícia");

        jInternalFrameCadastroPedido.setVisible(true);

        jLabelCadastroPedido.setText("Nome do Pedido");

        jTextFieldCadastroPedidoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroPedidoNomeActionPerformed(evt);
            }
        });

        jLabelCadastroPedidoPreco.setText("Preço");

        jButtonCadastroPedidoSalvar.setText("Salvar");
        jButtonCadastroPedidoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPedidoSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroCancelar.setText("Cancelar");
        jButtonCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroPedidoLayout = new javax.swing.GroupLayout(jInternalFrameCadastroPedido.getContentPane());
        jInternalFrameCadastroPedido.getContentPane().setLayout(jInternalFrameCadastroPedidoLayout);
        jInternalFrameCadastroPedidoLayout.setHorizontalGroup(
            jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroPedidoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCadastroPedidoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroPedidoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroPedidoSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroCancelar)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jInternalFrameCadastroPedidoLayout.setVerticalGroup(
            jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroPedido)
                    .addComponent(jTextFieldCadastroPedidoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroPedidoPreco)
                    .addComponent(jTextFieldCadastroPedidoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jInternalFrameCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroPedidoSalvar)
                    .addComponent(jButtonCadastroCancelar))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jDesktopPane.setLayer(jInternalFrameCadastroPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroPedido)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroPedido)
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroPedido.setText("Pedido");
        jMenuItemCadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPedidoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroPedido);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEditar.setText("Editar");

        jMenuItemEditarPedido.setText("Pedido");
        jMenuEditar.add(jMenuItemEditarPedido);

        jMenuBarPrincipal.add(jMenuEditar);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarPedido.setText("Pedido");
        jMenuPesquisar.add(jMenuItemPesquisarPedido);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuItemVendasCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasCarrinhoActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVendasCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVendasCarrinhoActionPerformed

    private void jTextFieldCadastroPedidoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroPedidoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroPedidoNomeActionPerformed

    private void jButtonCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCancelarActionPerformed
        // TODO add your handling code here:
         jTextFieldCadastroPedidoNome.setText("");
         jTextFieldCadastroPedidoPreco.setText("");
         jInternalFrameCadastroPedido.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroCancelarActionPerformed

    private void jMenuItemCadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPedidoActionPerformed
         jInternalFrameCadastroPedido.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroPedidoActionPerformed

    private void jButtonCadastroPedidoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPedidoSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroPedidoNome.getText();
        if(nome.equals("")){
            JOptionPane.showMessageDialog(rootPane, "O campo Nome do Pedido está vazio!");
        }else{
            String preco = jTextFieldCadastroPedidoPreco.getText();
            
            if(preco.equals("")){
                JOptionPane.showMessageDialog(rootPane, "O campo Preço está vazio!");
            }else{
                try{
                    double precoConvertido = Double.parseDouble(preco);
                    Pedido pedido = new Pedido(nome, precoConvertido);
                    pedido.apresentarPedido();
                    
                    jTextFieldCadastroPedidoNome.setText("");
                    jTextFieldCadastroPedidoPreco.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane, "O Pedido "+nome+" foi cadastrado com sucesso!");
                    
                    jInternalFrameCadastroPedido.setVisible(false);
                    
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Preencha o preço do pedido com números separados por pontos ao invés de vírgula!");
                }
            }
        }
        
    }//GEN-LAST:event_jButtonCadastroPedidoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GUIMenu janelaPrincipal = new GUIMenu();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                janelaPrincipal.setVisible(true);
                janelaPrincipal.jInternalFrameCadastroPedido.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCancelar;
    private javax.swing.JButton jButtonCadastroPedidoSalvar;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jInternalFrameCadastroPedido;
    private javax.swing.JLabel jLabelCadastroPedido;
    private javax.swing.JLabel jLabelCadastroPedidoPreco;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemCadastroPedido;
    private javax.swing.JMenuItem jMenuItemEditarPedido;
    private javax.swing.JMenuItem jMenuItemPesquisarPedido;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JTextField jTextFieldCadastroPedidoNome;
    private javax.swing.JTextField jTextFieldCadastroPedidoPreco;
    // End of variables declaration//GEN-END:variables
}
